[tool.poetry]
name = "greentech"
version = "0.1.0"
description = ""
authors = ["Anders Jess Pedersen <anders.j.pedersen@alexandra.dk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
